### ISSUE TITLE
Align using tabs (no spaces)

### ISSUE THREAD

**Issue by chrismadrigal** [jarod2d/sublime_valign#38]
I there a setting for using tabs instead of spaces for alignment?

**Comment by jarod2d** [comment]
There's not currently -- I wouldn't recommend aligning with tabs, since the number of spaces that tabs render as is defined per-user, so your code might not be aligned depending on the viewer's settings. This also makes it tricky for the plugin to perform alignment with tabs. It can use whatever the current setting is for the number of spaces per tab, but again, if that ever changes, the alignment will be broken.

For those reasons, I don't plan on adding support for tab-based alignment, but you're welcome to fork the plugin and add that functionality yourself if you want to. Sorry!
